/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.paragon.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.json.JSONArray;

import com.paragon.dao.HouseExtrainfoDAO;
import com.paragon.dao.HouseInfoDAO;
import com.paragon.dao.UserConnHouseDAO;
import com.paragon.dao.User_InfoDAO;
import com.paragon.entity.HouseExtrainfo;
import com.paragon.entity.HouseInfo;
import com.paragon.entity.User_Info;
import com.paragon.struts.form.House_exInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-17-2014
 * 
 * XDoclet definition:
 * @struts.action path="/house_exInfo" name="house_exInfoForm" input="/form/house_exInfo.jsp" parameter="method" scope="request" validate="true"
 */
public class House_exInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		House_exInfoForm house_exInfoForm = (House_exInfoForm) form;// TODO Auto-generated method stub
		
//		UserConnHouse user_c_house = new UserConnHouse();
		
		
		
		UserConnHouseDAO  user_c_housedao = new UserConnHouseDAO();
		//i=Integer.parseInt(s);
		int i = Integer.parseInt(house_exInfoForm.getHouse_id());		
		int userID =  user_c_housedao.findbyhouseId(i);
		
		
		System.out.print(userID);
		
		//查询用户信息
		User_InfoDAO  user_infodao = new User_InfoDAO();
		User_Info userinfo = new User_Info();
		userinfo = user_infodao.queryById(userID);
		
		
		//查询房屋详情
		HouseExtrainfoDAO hou_info = new HouseExtrainfoDAO();
		//queryById
		HouseExtrainfo hou_detail = new HouseExtrainfo();
		hou_detail = hou_info.queryById(i);
		//查询房屋基本信息
		HouseInfo house = new HouseInfo();
		HouseInfoDAO housedao = new HouseInfoDAO();
		house=housedao.queryById(i);
		
		JSONArray result = new JSONArray();
		
		
		
		Map uinfo = new HashMap();
		uinfo.put("user_phone", userinfo.getUser_Phone());
		uinfo.put("user_tname", userinfo.getUser_TName());
		uinfo.put("user_address", userinfo.getUser_Address());
		uinfo.put("user_gender", userinfo.getSex());
		JSONArray uinfoJson = new JSONArray();
		uinfoJson.put(uinfo);
		
		Map hinfo = new HashMap();
		hinfo.put("facilities", hou_detail.getFacilities());
		hinfo.put("bed_num", hou_detail.getBedNum());
		hinfo.put("toilet_num", hou_detail.getToiletNum());
		hinfo.put("room_describe", hou_detail.getRoomDescribe());
		JSONArray hinfoJson = new JSONArray();
		hinfoJson.put(hinfo);
		
		Map houseinfo = new HashMap();
		houseinfo.put("address", house.getHouseAddress());
		houseinfo.put("intro", house.getHouseIntro());
		houseinfo.put("price", house.getHousePrice());
		houseinfo.put("livenum", house.getLiveNum());
		houseinfo.put("picture", house.getHousePicture());
		houseinfo.put("checkInTime", house.getCheckInTime());
		houseinfo.put("checkOutTime", house.getCheckOutTime());
		houseinfo.put("houseType", house.getHouseType());
		houseinfo.put("rentType", house.getRentType());
		houseinfo.put("houseArea", house.getHouseArea());
		houseinfo.put("bedroomNum", house.getBedroomNum());
		JSONArray houseinfoJson = new JSONArray();
		houseinfoJson.put(houseinfo);
		
		Map result_map = new HashMap();
		result_map.put("user", uinfoJson);
		result_map.put("house", hinfoJson);
		result_map.put("house_info", houseinfoJson);
//		Map map_result = new HashMap();
//		map_result.put("user_infor", uinfo);
//		map_result.put("house_detail", hinfo);	
		
		result.put(result_map);	
		String respon_result = "{\"House_ExtraInfo\":"+ result +"}";	 
		 System.out.print(userinfo.getUser_Phone());
		 //
		 response.setContentType("text/html; charset=utf-8");
		 
		try {
			PrintWriter out = response.getWriter();
		    out.print(respon_result);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		return null;
	}
}