/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.paragon.struts.action;



import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.paragon.dao.UserDAO;
import com.paragon.dao.User_InfoDAO;
import com.paragon.entity.User;
import com.paragon.entity.User_Info;
import com.paragon.struts.form.RegistForm;



/** 
 * MyEclipse Struts
 * Creation date: 01-13-2014
 * 
 * XDoclet definition:
 * @struts.action path="/regist" name="registForm" input="/regist.jsp" parameter="method" scope="request" validate="true"
 */
public class RegistAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		 RegistForm registForm = (RegistForm) form;// TODO Auto-generated method stub
		 //User_Register table attribute
		 int userid = registForm.getUser_id();
		 String user_regname = registForm.getUser_regname();
		 String password = registForm.getPassword();
		 String email = registForm.getEmail();
		 
		 //User_Info attribute
		 String usertname = registForm.getUser_tname();
		 String sex = registForm.getSex();
		 String userphone = registForm.getUser_phone();
		 String useraddress = registForm.getUser_address();
		 int check;
		 boolean flag = false;
		 //Insert User_Register table
		 UserDAO userdao = new UserDAO();
		 User user = new User();
		 
		 user.setUser_ID(userid);
		 user.setUser_RegName(user_regname);
		 user.setPassword(password);
		 user.setEmail(email);
		 userdao.insert(user);
		 //Insert User_Info table
		 User_InfoDAO user_infodao = new User_InfoDAO();
		 User_Info user_info = new User_Info();
		 
		 user_info.setUser_ID(userid);
		 user_info.setUser_TName(usertname);
		 user_info.setSex(sex);
		 user_info.setUser_Phone(userphone);
		 user_info.setUser_Address(useraddress);
		 response.setContentType("text/html; charset=utf-8");
		 
		 if(user.getEmail() == "" || user.getPassword()==""|| user.getUser_RegName()=="")
		 {
			 flag = false;
		 }
		 else{
			 user_infodao.insert(user_info);
			 flag =true;
		 }
		 
			if (flag) check = 1;
			else check = 0;		
			try {
				PrintWriter out = response.getWriter();
			    out.println(check);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
		
		return null;
	}
}