/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.paragon.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-13-2014
 * 
 * XDoclet definition:
 * @struts.form name="PublishForm"
 */
public class PublishForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	//House_Info table
	private int house_id;
	private int user_id;
	private String house_address;
	private String house_picture;
	private int live_num;
	private int house_price;
	private String house_intro;
	private String check_in_time;
	private String check_out_time;
	private String house_type;
	private String rent_type;
	private int house_area;
	private int bedroom_num;
	
	//House_ExtraInfo table
	private String facilities;
	private int bed_num;
	private int toilet_num;
	private String room_describe;
	

	public int getHouse_id() {
		return house_id;
	}

	public void setHouse_id(int house_id) {
		this.house_id = house_id;
	}

	public String getHouse_address() {
		return house_address;
	}

	public void setHouse_address(String house_address) {
		this.house_address = house_address;
	}

	public String getHouse_picture() {
		return house_picture;
	}

	public void setHouse_picture(String house_picture) {
		this.house_picture = house_picture;
	}

	public int getLive_num() {
		return live_num;
	}

	public void setLive_num(int live_num) {
		this.live_num = live_num;
	}

	public int getHouse_price() {
		return house_price;
	}

	public void setHouse_price(int house_price) {
		this.house_price = house_price;
	}

	public String getHouse_intro() {
		return house_intro;
	}

	public void setHouse_intro(String house_intro) {
		this.house_intro = house_intro;
	}

	public String getCheck_in_time() {
		return check_in_time;
	}

	public void setCheck_in_time(String check_in_time) {
		this.check_in_time = check_in_time;
	}

	public String getCheck_out_time() {
		return check_out_time;
	}

	public void setCheck_out_time(String check_out_time) {
		this.check_out_time = check_out_time;
	}

	public String getHouse_type() {
		return house_type;
	}

	public void setHouse_type(String house_type) {
		this.house_type = house_type;
	}

	public String getRent_type() {
		return rent_type;
	}

	public void setRent_type(String rent_type) {
		this.rent_type = rent_type;
	}

	public int getHouse_area() {
		return house_area;
	}

	public void setHouse_area(int house_area) {
		this.house_area = house_area;
	}

	public int getBedroom_num() {
		return bedroom_num;
	}

	public void setBedroom_num(int bedroom_num) {
		this.bedroom_num = bedroom_num;
	}

	public String getFacilities() {
		return facilities;
	}

	public void setFacilities(String facilities) {
		this.facilities = facilities;
	}

	public int getBed_num() {
		return bed_num;
	}

	public void setBed_num(int bed_num) {
		this.bed_num = bed_num;
	}

	public int getToilet_num() {
		return toilet_num;
	}

	public void setToilet_num(int toilet_num) {
		this.toilet_num = toilet_num;
	}

	public String getRoom_describe() {
		return room_describe;
	}

	public void setRoom_describe(String room_describe) {
		this.room_describe = room_describe;
	}

	/** 
	 * Method valiString
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors valiString(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public int getUser_id() {
		return user_id;
	}

	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}
}